#!/usr/bin/env python3
"""Generate gckpp_Interleaved.F90: interleaved-layout (_I) variants of the
four hot per-cell kernels, for the coalesced-memory GPU experiment.

Run inside KPP-Standalone-batch/ AFTER patch_sources.py.

Transformation (mechanical, per routine):
  - routine gains leading args (ic, nP); per-cell arrays become 2D with the
    cell index FIRST: NAME(expr) -> NAME(ic, expr).  Thread ic then touches
    addresses adjacent to thread ic+1 for the same expr => coalesced.
  - routine-local scratch arrays (A in Fun_SPLIT, B in Jac_SP, W in
    KppDecomp) become caller-provided global scratch, also (nP, :) --
    a per-thread local would defeat the layout experiment.
  - KppSolve_I additionally takes 'noff' because the integrator passes a
    stage slice of Kw: X(n) -> X(ic, noff+n).
  - operation ORDER per cell is untouched -> results must stay bit-exact.

Bodies are extracted verbatim from the patched generated sources; only the
declared array names are index-rewritten (case-sensitive regex, exact-name
word boundary, literal '(' required).
"""
import re, sys

def read(f):
    return open(f).read()

def extract(src, start_pat, end_pat):
    m0 = re.search(start_pat, src)
    if not m0:
        sys.exit('extract: start not found: %s' % start_pat)
    m1 = re.search(end_pat, src[m0.end():])
    if not m1:
        sys.exit('extract: end not found: %s' % end_pat)
    return src[m0.end():m0.end()+m1.start()]

def body_after(text, anchor):
    i = text.find(anchor)
    if i < 0:
        sys.exit('body_after: anchor not found: %s' % anchor)
    return text[i+len(anchor):]

def interleave(body, names, repl='(ic,'):
    for n in names:
        body = re.sub(r'\b%s\(' % re.escape(n), '%s%s' % (n, repl), body)
    return body

# ---------------------------------------------------------------- Fun_SPLIT
src = read('gckpp_Function.F90')
t = extract(src, r'(?m)^SUBROUTINE Fun_SPLIT \(', r'(?m)^END SUBROUTINE Fun_SPLIT\b')
t = body_after(t, '! Computation of equation rates')
# drop optional-Aout copy-back (Aout dropped from the _I signature)
t = re.sub(r'(?m)^\s*IF \( PRESENT\( Aout \) \) Aout = A\s*$', '', t)
if '\n  Vdot = P_VAR - D_VAR*V\n' not in t:
    sys.exit('Fun_SPLIT: expected whole-array Vdot statement not found')
# interleave FIRST (the whole-array line has no parens so it is untouched),
# THEN expand it to an explicit loop -- avoids double-rewriting
t = interleave(t, ['A', 'V', 'F', 'RCT', 'Vdot', 'P_VAR', 'D_VAR'])
fun_body = t.replace('\n  Vdot = P_VAR - D_VAR*V\n',
              '\n  DO kv_i = 1, NVAR\n'
              '    Vdot(ic,kv_i) = P_VAR(ic,kv_i) - D_VAR(ic,kv_i)*V(ic,kv_i)\n'
              '  ENDDO\n')

# ------------------------------------------------------------------ Jac_SP
src = read('gckpp_Jacobian.F90')
t = extract(src, r'(?m)^SUBROUTINE Jac_SP \(', r'(?m)^END SUBROUTINE Jac_SP\s*$')
mB = re.search(r'REAL\(kind=dp\) :: B\((\d+)\)', t)
if not mB:
    sys.exit('Jac_SP: local B(...) not found')
NB_JAC = int(mB.group(1))
t = body_after(t, mB.group(0))
jac_body = interleave(t, ['V', 'F', 'RCT', 'JVS', 'B'])

# --------------------------------------------------------------- KppDecomp
src = read('gckpp_LinearAlgebra.F90')
t = extract(src, r'(?m)^SUBROUTINE KppDecomp\(', r'(?m)^END SUBROUTINE KppDecomp\s*$')
t = body_after(t, 'INTEGER  :: k, kk, j, jj')
dec_body = interleave(t, ['JVS', 'W'])

# ---------------------------------------------------------------- KppSolve
t = extract(src, r'(?m)^SUBROUTINE KppSolve \(', r'(?m)^END SUBROUTINE KppSolve\s*$')
t = body_after(t, 'REAL(kind=dp) :: X(NVAR)')
t = interleave(t, ['JVS'])
t = interleave(t, ['X'], repl='(ic,noff+')
sol_body = t

# ------------------------------------------------------------------ output
out = '''!------------------------------------------------------------------------------
! gckpp_Interleaved.F90 -- GENERATED by interleave_sources.py.  DO NOT EDIT.
!
! Interleaved-layout (cell-index-first) variants of the four hot per-cell
! kernels.  Bodies are verbatim copies of the patched generated sources with
! every per-cell array access NAME(expr) rewritten to NAME(ic, expr), so the
! per-cell operation order (and therefore the arithmetic) is IDENTICAL.
!------------------------------------------------------------------------------
MODULE gckpp_Interleaved

  USE gckpp_Precision,  ONLY : dp
  USE gckpp_Parameters
  USE gckpp_JacobianSP
  IMPLICIT NONE

  ! Auto-reduce masks, constant-folded (AR is off in all harvested cells;
  ! same treatment as patch_sources.py applies to the 1-cell kernels)
  LOGICAL, PARAMETER :: DO_FUN({NF}) = .TRUE.
  LOGICAL, PARAMETER :: DO_JVS({NJ}) = .TRUE.
  LOGICAL, PARAMETER :: DO_SLV({NS}) = .TRUE.

  ! Size of the Jac_SP temporary array B (from the generated source)
  INTEGER, PARAMETER :: NB_JAC = {NB}

CONTAINS

SUBROUTINE Fun_SPLIT_I ( ic, nP, V, F, RCT, Vdot, P_VAR, D_VAR, A )
  !$acc routine seq
  INTEGER, INTENT(IN) :: ic, nP
  REAL(kind=dp) :: V(nP,NVAR)      ! variable species (interleaved)
  REAL(kind=dp) :: F(nP,NFIX)      ! fixed species (interleaved)
  REAL(kind=dp) :: RCT(nP,NREACT)  ! rate constants (interleaved)
  REAL(kind=dp) :: Vdot(nP,NVAR)
  REAL(kind=dp) :: P_VAR(nP,NVAR)
  REAL(kind=dp) :: D_VAR(nP,NVAR)
  REAL(kind=dp) :: A(nP,NREACT)    ! equation-rate scratch (global, interleaved)
  INTEGER :: kv_i
! Computation of equation rates
{FUN}
END SUBROUTINE Fun_SPLIT_I

SUBROUTINE Jac_SP_I ( ic, nP, V, F, RCT, JVS, B )
  !$acc routine seq
  INTEGER, INTENT(IN) :: ic, nP
  REAL(kind=dp) :: V(nP,NVAR)
  REAL(kind=dp) :: F(nP,NFIX)
  REAL(kind=dp) :: RCT(nP,NREACT)
  REAL(kind=dp) :: JVS(nP,LU_NONZERO)
  REAL(kind=dp) :: B(nP,NB_JAC)    ! temporary array (global, interleaved)
{JAC}
END SUBROUTINE Jac_SP_I

SUBROUTINE KppDecomp_I ( ic, nP, JVS, W, IER )
  !$acc routine seq
  INTEGER, INTENT(IN) :: ic, nP
  REAL(kind=dp) :: JVS(nP,LU_NONZERO)
  REAL(kind=dp) :: W(nP,NVAR)      ! row scratch (global, interleaved)
  INTEGER  :: IER
  REAL(kind=dp) :: a
  INTEGER  :: k, kk, j, jj
{DEC}
END SUBROUTINE KppDecomp_I

SUBROUTINE KppSolve_I ( ic, nP, noff, JVS, X )
  !$acc routine seq
  INTEGER, INTENT(IN) :: ic, nP, noff
  REAL(kind=dp) :: JVS(nP,LU_NONZERO)
  REAL(kind=dp) :: X(nP,*)         ! stage vector inside Kw: X(ic, noff+1..noff+NVAR)
{SOL}
END SUBROUTINE KppSolve_I

END MODULE gckpp_Interleaved
'''.format(NF=353, NJ=5683, NS=354, NB=NB_JAC,
           FUN=fun_body.rstrip(), JAC=jac_body.rstrip(),
           DEC=dec_body.rstrip(), SOL=sol_body.rstrip())

open('gckpp_Interleaved.F90', 'w').write(out)
print('generated gckpp_Interleaved.F90  (NB_JAC=%d)' % NB_JAC)
print('ALL_INTERLEAVED')
